"use client"

/**
 * The send primitive, end to end.
 *
 * Creating a send and opening one are the only two operations this product
 * really has, so both live here in full rather than being spread across the UI.
 */

import {
  generateLinkSecret,
  open,
  splitContentKey,
  joinContentKey,
  deriveAuthKey,
  deriveCodeProof,
  unwrapContentKey,
  blindAttribute,
  toBase64Url,
  fromBase64Url,
  packEntityKey,
  unpackEntityKey,
} from "./crypto"
import { unpackEnvelope, type PackedFile } from "./envelope"
import { uploadEncryptedBlob, fetchBlobFromGateway } from "./swarm"
import {
  buildGrantBinding,
  createGrant,
  createThresholdGrant,
  deleteGrant,
  getCurrentBlock,
  getGrant,
  listGrants,
  MalformedGrantError,
  type FileKind,
  type Grant,
  type ThresholdGrantPayload,
} from "./arkiv"
import { getIdentity, ensureFunded } from "./identity"
import { revokeMessage } from "./revoke"
import { shareMessage } from "./share"
import { privateKeyToAccount } from "viem/accounts"
import { type DocumentRecord, type SetAsideIdentifiers } from "./archive"
import { createEncryptedAsset, createEncryptedAssetFromArchive, type EncryptedAsset } from "./assets"
import { protectGrantShare, releaseGrantShare } from "./grant-package"
import {
  selectProtectingProvider,
  selectReleasingProvider,
  readChipotleConfig,
  ChipotleUnavailableError,
  TacoUnavailableError,
} from "./key-release/index"
import type { GrantBinding } from "./key-release/types"

const IV_BYTES = 12

export type CreateSendResult = {
  entityKey: string
  txHash: string
  expiresAt: number
  swarmRef: string
  /** The full share URL, link secret in the fragment. Never sent to a server. */
  url: string
  /** H-7: the code the sender must relay separately from the link. Absent when they chose not to add one. */
  code?: string
  /**
   * H-36: what import set aside, per file that actually had something to set
   * aside. Never travels — this is what the sender is shown, not what the
   * recipient receives.
   */
  setAside: { fileName: string; setAside: SetAsideIdentifiers }[]
}

export type SendProgress = (stage: string) => void

type CreateSendDependencies = {
  fetch: typeof fetch
  getIdentity: typeof getIdentity
  uploadEncryptedBlob: typeof uploadEncryptedBlob
  createGrant: typeof createGrant
  /** H-69: the Chipotle-enabled branch of `createSendFromArchive` only. */
  getCurrentBlock: typeof getCurrentBlock
  createThresholdGrant: typeof createThresholdGrant
  selectProtectingProvider: typeof selectProtectingProvider
}

const defaultCreateSendDependencies: CreateSendDependencies = {
  fetch,
  getIdentity,
  uploadEncryptedBlob,
  createGrant,
  getCurrentBlock,
  createThresholdGrant,
  selectProtectingProvider,
}

/**
 * Reach the holder store itself before any send work starts.
 *
 * H-58/R3-003: an earlier version of this posted an empty body and treated a
 * 400 as healthy. That only proved the route was configured and parsed the
 * request — `validateShareRequest` rejects `{}` before `putShare` is ever
 * called, so it passed even with Redis down. The route's `GET` (see
 * `app/api/holder/share/route.ts`) pings the store directly instead, so a
 * dead store is reported as unavailable here rather than discovered after the
 * grant and ciphertext are already written.
 */
async function preflightHolder(request: typeof fetch): Promise<void> {
  let response: Response
  try {
    response = await request("/api/holder/share", { method: "GET" })
  } catch (error) {
    throw new Error(`The key-share holder is unavailable: ${(error as Error).message}`)
  }

  if (response.ok) return

  const detail = await response.json().catch(() => ({}))
  throw new Error(
    `The key-share holder is unavailable: ${detail?.error ?? `HTTP ${response.status}`}`,
  )
}

/**
 * Encrypt → Swarm → grant → link.
 *
 * Note the order: the bytes are encrypted before they leave the browser, the
 * ciphertext goes straight to Swarm from the browser, and only then is a grant
 * written. Our own origin is never in the path of the plaintext, which is the
 * claim the README makes and the reason this app has no upload endpoint.
 *
 * H-53 moved the pack/encrypt/upload step into `lib/assets.ts`
 * (`createEncryptedAsset`), so this function is now that call followed by one
 * grant issued against the asset it returns — behaviorally identical to
 * before, since nothing here reuses the asset for a second grant. See
 * `createThresholdSend` for the path that does.
 */
export async function createSend(
  params: {
    files: File[]
    recipientLabel: string
    ttlSeconds: number
    /** H-7: a four-digit code, generated by the caller (`generateCode`), sent separately from the link. */
    code?: string
    /** The sender's own account name, if known — passed to `importDocument` so an unlabeled mention of it is caught too (H-28). */
    accountName?: string
    onProgress?: SendProgress
  },
  dependencyOverrides: Partial<CreateSendDependencies> = {},
): Promise<CreateSendResult> {
  const progress = params.onProgress ?? (() => {})
  if (params.files.length === 0) throw new Error("Pick at least one document")

  const dependencies = { ...defaultCreateSendDependencies, ...dependencyOverrides }
  progress("Checking key-share holder")
  await preflightHolder(dependencies.fetch)

  const identity = await dependencies.getIdentity()

  const asset = await createEncryptedAsset(
    { files: params.files, accountName: params.accountName, onProgress: progress },
    { uploadEncryptedBlob: dependencies.uploadEncryptedBlob },
  )

  progress("Splitting key")
  // The content key is split, never wrapped-and-published. One half is derived
  // from the fragment; the other goes to a holder that can delete it. Nothing
  // secret is written to Arkiv, so there is nothing for calldata to preserve.
  //
  // When this send carries a code (H-7), it is folded into the link half here
  // — never into `authKey` or `commitment`, which stay over the link secret
  // alone. The commitment written to Arkiv below is therefore identical
  // whether or not a code was chosen; nothing about the code ever reaches it.
  const linkSecret = generateLinkSecret()
  const { heldShare, authKey, commitment } = await splitContentKey(asset.contentKey, linkSecret, params.code)

  // Topping up the user's own key is bookkeeping, not a step they took. It is
  // deliberately not narrated: the previous stage label stays on screen.
  await ensureFunded(identity.address)

  progress("Writing grant to Arkiv")
  const grant = await dependencies.createGrant({
    privateKey: identity.privateKey,
    payload: { v: 2, ref: asset.ref, authCommitment: commitment },
    fileKind: asset.fileKind,
    recipientBlind: await blindAttribute(identity.blindKey, params.recipientLabel),
    labelBlind: await blindAttribute(identity.blindKey, asset.labelSource),
    fileCount: asset.fileCount,
    ttlSeconds: params.ttlSeconds,
  })

  // The share goes to the holder only once the grant exists, so the holder can
  // always resolve an entity key to a live grant. If this fails the send is
  // unreadable by anyone — including us — which is the correct failure.
  //
  // Proof of ownership is the same signed-entity-key scheme "End access now"
  // uses, with its own "share" action string — see lib/share.ts — so this
  // signature cannot be replayed against revoke or the access log, or vice
  // versa.
  progress("Handing the key share to the holder")
  const shareTimestamp = Math.floor(Date.now() / 1000)
  // The holder never learns the code — only this proof, salted with the auth
  // key it already sees on every unlock — and checks future attempts against
  // it, rate-limited. See `deriveCodeProof` and `lib/holder-store.ts`.
  const codeHash = params.code ? await deriveCodeProof(authKey, params.code) : undefined
  const sharePayload = {
    share: toBase64Url(heldShare),
    commitment,
    ttlSeconds: params.ttlSeconds,
    ...(codeHash ? { codeHash } : {}),
  }
  const shareSignature = await privateKeyToAccount(identity.privateKey).signMessage({
    message: shareMessage(grant.entityKey, shareTimestamp, sharePayload),
  })
  const handoff = await dependencies.fetch("/api/holder/share", {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({
      entityKey: grant.entityKey,
      ...sharePayload,
      signature: shareSignature,
      timestamp: shareTimestamp,
    }),
  })
  if (!handoff.ok) {
    const detail = await handoff.json().catch(() => ({}))
    throw new Error(
      `The grant was written but the key share was not stored, so this send cannot be opened: ${
        detail?.error ?? handoff.status
      }`,
    )
  }

  const url = `${window.location.origin}/s/${packEntityKey(grant.entityKey)}#${toBase64Url(
    linkSecret,
  )}`
  progress("Done")

  return { ...grant, swarmRef: asset.ref, url, code: params.code, setAside: asset.setAside }
}

/**
 * Send a send built from selections already in the sender's archive — H-64.
 *
 * Deliberately a separate function rather than a `files`/`documents` union
 * threaded through `createSend`: the two read different sources (a picked
 * `File[]` versus already-imported `DocumentRecord[]`), pack through a
 * different asset builder (`createEncryptedAssetFromArchive`, which skips
 * `importForAsset`'s cleaning step entirely — see that function's own
 * comment), and this story's brief asks for an additive path so H-53's
 * concurrent edits to this file have nothing here to conflict with. Every
 * step from "split the key" onward is the same handoff `createSend` performs,
 * copied rather than shared for the same reason — see this story's
 * `## Choices`.
 *
 * H-69: when Chipotle is enabled *and* this share carries no code, it takes
 * the live-key-release branch instead — a fresh v3, threshold-release grant
 * with no holder hand-off at all, sharing its bind/protect/write-grant shape
 * with `createThresholdSend` (`protectAndWriteThresholdGrant`) rather than a
 * third copy of it. A coded share always stays on the path below regardless
 * of the flag: the four-digit code (H-7) is enforced by the holder's own
 * attempt counter, which Chipotle has no equivalent of. With Chipotle
 * disabled, this function's holder path below is unchanged byte-for-byte.
 */
export async function createSendFromArchive(
  params: {
    documents: DocumentRecord[]
    recipientLabel: string
    ttlSeconds: number
    /** H-7: a four-digit code, generated by the caller (`generateCode`), sent separately from the link. */
    code?: string
    onProgress?: SendProgress
  },
  dependencyOverrides: Partial<CreateSendDependencies> = {},
): Promise<CreateSendResult> {
  const progress = params.onProgress ?? (() => {})
  if (params.documents.length === 0) throw new Error("Pick at least one document")

  const dependencies = { ...defaultCreateSendDependencies, ...dependencyOverrides }

  if (readChipotleConfig().enabled && !params.code) {
    const asset = await createEncryptedAssetFromArchive(params.documents, progress, {
      uploadEncryptedBlob: dependencies.uploadEncryptedBlob,
    })
    const threshold = await protectAndWriteThresholdGrant(
      asset,
      { recipientLabel: params.recipientLabel, ttlSeconds: params.ttlSeconds, onProgress: progress },
      {
        getIdentity: dependencies.getIdentity,
        ensureFunded,
        getCurrentBlock: dependencies.getCurrentBlock,
        createThresholdGrant: dependencies.createThresholdGrant,
        selectProtectingProvider: dependencies.selectProtectingProvider,
      },
    )
    return {
      entityKey: threshold.entityKey,
      txHash: threshold.txHash,
      expiresAt: threshold.expiresAt,
      swarmRef: threshold.swarmRef,
      url: threshold.url,
      setAside: [],
    }
  }

  progress("Checking key-share holder")
  await preflightHolder(dependencies.fetch)

  const identity = await dependencies.getIdentity()

  const asset = await createEncryptedAssetFromArchive(params.documents, progress, {
    uploadEncryptedBlob: dependencies.uploadEncryptedBlob,
  })

  progress("Splitting key")
  // A brand-new share key, generated fresh right here — never the archive key,
  // which opened the documents above and goes no further than this function's
  // own stack. See the operator's model in the story brief.
  const linkSecret = generateLinkSecret()
  const { heldShare, authKey, commitment } = await splitContentKey(asset.contentKey, linkSecret, params.code)

  await ensureFunded(identity.address)

  progress("Writing grant to Arkiv")
  const grant = await dependencies.createGrant({
    privateKey: identity.privateKey,
    payload: { v: 2, ref: asset.ref, authCommitment: commitment },
    fileKind: asset.fileKind,
    recipientBlind: await blindAttribute(identity.blindKey, params.recipientLabel),
    labelBlind: await blindAttribute(identity.blindKey, asset.labelSource),
    fileCount: asset.fileCount,
    ttlSeconds: params.ttlSeconds,
  })

  progress("Handing the key share to the holder")
  const shareTimestamp = Math.floor(Date.now() / 1000)
  const codeHash = params.code ? await deriveCodeProof(authKey, params.code) : undefined
  const sharePayload = {
    share: toBase64Url(heldShare),
    commitment,
    ttlSeconds: params.ttlSeconds,
    ...(codeHash ? { codeHash } : {}),
  }
  const shareSignature = await privateKeyToAccount(identity.privateKey).signMessage({
    message: shareMessage(grant.entityKey, shareTimestamp, sharePayload),
  })
  const handoff = await dependencies.fetch("/api/holder/share", {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({
      entityKey: grant.entityKey,
      ...sharePayload,
      signature: shareSignature,
      timestamp: shareTimestamp,
    }),
  })
  if (!handoff.ok) {
    const detail = await handoff.json().catch(() => ({}))
    throw new Error(
      `The grant was written but the key share was not stored, so this send cannot be opened: ${
        detail?.error ?? handoff.status
      }`,
    )
  }

  const url = `${window.location.origin}/s/${packEntityKey(grant.entityKey)}#${toBase64Url(
    linkSecret,
  )}`
  progress("Done")

  return { ...grant, swarmRef: asset.ref, url, code: params.code, setAside: [] }
}

export type OpenedSend = {
  files: PackedFile[]
  expiresAt: number
  fileKind: FileKind
}

export type OpenFailure =
  | { status: "expired" }
  /** The sender ended this share early. Distinct from a lapsed grant — see H-29/H-35. */
  | { status: "revoked" }
  | { status: "no-key" }
  /** H-7: this share carries a code and none was presented. Ask for it before anything renders. */
  | { status: "needs-code"; expiresAt: number }
  /**
   * H-7: a code was presented and did not match. Its own status — never the
   * generic "error" a decryption failure would otherwise produce, and never
   * "expired" or "unavailable" either. `locked` means every further attempt
   * is refused for the rest of this grant's life, not just this one.
   */
  | { status: "wrong-code"; expiresAt: number; locked: boolean }
  /** The holder is unreachable. Distinct from expiry, and must stay distinct. */
  | { status: "unavailable"; message: string }
  | { status: "error"; message: string }

type OpenSendDependencies = {
  getGrant: typeof getGrant
  getCurrentBlock: typeof getCurrentBlock
  fetchBlobFromGateway: typeof fetchBlobFromGateway
  selectReleasingProvider: typeof selectReleasingProvider
}

const defaultOpenSendDependencies: OpenSendDependencies = {
  getGrant,
  getCurrentBlock,
  fetchBlobFromGateway,
  selectReleasingProvider,
}

/**
 * Open a send.
 *
 * The two halves have to meet here: the link secret from the URL fragment and
 * the wrapped key from the Arkiv grant. A missing grant is the ordinary,
 * expected outcome once the window closes — it is reported as "expired" rather
 * than as an error, because nothing went wrong.
 *
 * `dependencyOverrides` exists only so `scripts/taco-unlock-proof.mjs` can
 * drive the v3 branch offline, the same seam `createSend`'s
 * `CreateSendDependencies` already uses; app code never passes it.
 */
export async function openSend(
  entityKeyOrShort: string,
  linkSecretB64: string,
  /** H-7: presented once the reader has typed the code this share requires. */
  code?: string,
  dependencyOverrides: Partial<OpenSendDependencies> = {},
): Promise<{ status: "ok"; send: OpenedSend } | OpenFailure> {
  if (!linkSecretB64) return { status: "no-key" }

  const dependencies = { ...defaultOpenSendDependencies, ...dependencyOverrides }

  // Links carry the entity key in base64url; older ones carry hex. Both resolve
  // to the same 32 bytes.
  let entityKey: string
  try {
    entityKey = unpackEntityKey(entityKeyOrShort)
  } catch {
    return { status: "error", message: "This link does not contain a valid grant reference." }
  }

  let grant: Grant | null
  try {
    grant = await dependencies.getGrant(entityKey)
  } catch (error) {
    if (error instanceof MalformedGrantError) {
      // The grant is live and we read it — the data itself is broken, which is a
      // concrete, nameable failure rather than an unknown one.
      return { status: "error", message: error.message }
    }
    // Anything else here — a wrong RPC URL, a proxy's error page, a timeout, a
    // query the node itself rejected — never confirmed the grant is gone. Saying
    // "expired" would tell the reader their access ended when in fact we cannot
    // tell, and the error screen's own copy ("the grant was found") would be a
    // claim we never verified either. Unavailable is the honest answer.
    return { status: "unavailable", message: (error as Error).message }
  }
  if (!grant) return { status: "expired" }

  try {
    // Check the boundary the engine enforces, not a wall clock.
    //
    // Honest-client hygiene, not enforcement: a reader who controls their own
    // browser can skip it, and anyone holding an archived copy of the grant
    // payload never asks us at all. It keeps the ordinary case truthful; the
    // cryptography does not depend on it.
    if (grant.expiresBlock > 0) {
      const head = await dependencies.getCurrentBlock()
      if (Number(head) >= grant.expiresBlock) return { status: "expired" }
    }

    const linkSecret = fromBase64Url(linkSecretB64)
    const payload = grant.payload

    let contentKey: Uint8Array
    if (grant.legacy) {
      // A v1 grant published its wrapped key on-chain. It still opens, and it
      // still cannot expire — which is exactly why the format changed.
      const wrap = (payload as { wrap: { iv: string; ct: string } }).wrap
      contentKey = await unwrapContentKey(
        { iv: fromBase64Url(wrap.iv), ciphertext: fromBase64Url(wrap.ct) },
        linkSecret,
        payload.ref,
      )
    } else if (payload.v === 3) {
      // v3: no holder at all. Whichever provider protected this share (its
      // own `payload.release.provider` says which — chosen here by the
      // factory, never by today's env, so a share protected under one
      // provider always releases through that same one) checks Arkiv's own
      // live state itself (see `buildArkivGrantQuery`) and releases the
      // complementary share only while that state still matches exactly what
      // this share was protected for — the head-boundary check above already
      // covers the ordinary, expected expiry, so nothing here calls the
      // provider once that has fired.
      const binding: GrantBinding = {
        grantId: payload.release.grantId,
        owner: grant.owner as `0x${string}`,
        expiresBlock: BigInt(grant.expiresBlock),
        ref: payload.ref,
      }
      try {
        const provider = dependencies.selectReleasingProvider(payload.release)
        const heldShare = await releaseGrantShare(payload.release, linkSecret, binding, provider)
        contentKey = await joinContentKey(heldShare, linkSecret)
      } catch (error) {
        if (error instanceof TacoUnavailableError || error instanceof ChipotleUnavailableError) {
          // Neither adapter ever claims a clean denial — see
          // lib/key-release/taco.ts and lib/key-release/chipotle.ts. The one
          // authoritative "expired" for a v3 grant is the head-boundary check
          // above; anything a provider itself reports is retryable
          // unavailability, never a second way to say expired.
          return { status: "unavailable", message: error.message }
        }
        throw error
      }
    } else {
      // Prove we hold the link, and ask the holder for the other half. Without
      // it there is no key to reconstruct — this is the expiry.
      //
      // Without a code, this is the one call it always was. With one, the
      // proof travels alongside it — the holder never sees the code itself,
      // only this hash (`deriveCodeProof`), and it is the same value with or
      // without `code` set here, since it derives from the auth key rather
      // than the presence of a code.
      const authKey = await deriveAuthKey(linkSecret)
      const codeProof = code ? await deriveCodeProof(authKey, code) : undefined
      let response: Response
      try {
        response = await fetch("/api/holder/unlock", {
          method: "POST",
          headers: { "content-type": "application/json" },
          body: JSON.stringify({
            entityKey,
            authKey: toBase64Url(authKey),
            ...(codeProof ? { codeProof } : {}),
          }),
        })
      } catch (error) {
        // The request never reached the holder, so there is no status and no body
        // to classify — the ordinary shape of an unreachable service, not of a
        // wrong link. Falling through to the generic catch below would report
        // this as a decryption failure, which is exactly the false claim this
        // story exists to remove.
        return { status: "unavailable", message: (error as Error).message }
      }

      if (response.status === 410) {
        // The holder tells the two apart (`lib/unlock.ts`); this is the one place
        // that flag is read back out, so the page can too.
        const detail = await response.json().catch(() => ({}))
        return detail?.revoked ? { status: "revoked" } : { status: "expired" }
      }
      if (response.status === 401) {
        // H-7: the holder's code gate, told apart the same way revoked/expired
        // are — one status code, a flag that says which. Neither case ever
        // reaches a share read or a decrypt attempt.
        const detail = await response.json().catch(() => ({}))
        if (detail?.codeRequired) return { status: "needs-code", expiresAt: grant.expiresAt }
        if (detail?.wrongCode) {
          return { status: "wrong-code", expiresAt: grant.expiresAt, locked: Boolean(detail?.locked) }
        }
        return { status: "error", message: detail?.error ?? "Unauthorized" }
      }
      if (!response.ok) {
        const detail = await response.json().catch(() => ({}))
        // A holder we cannot reach is not an expiry. Saying so would tell the
        // reader their access ended when we simply do not know.
        if (detail?.retryable || response.status >= 500) {
          return { status: "unavailable", message: detail?.error ?? `HTTP ${response.status}` }
        }
        return { status: "error", message: detail?.error ?? `HTTP ${response.status}` }
      }

      const { share } = (await response.json()) as { share: string }
      contentKey = await joinContentKey(fromBase64Url(share), linkSecret, code)
    }

    const blob = await dependencies.fetchBlobFromGateway(payload.ref)
    const envelope = await open(contentKey, {
      iv: blob.subarray(0, IV_BYTES),
      ciphertext: blob.subarray(IV_BYTES),
    })

    const files = unpackEnvelope(envelope)
    return {
      status: "ok",
      send: { files, expiresAt: grant.expiresAt, fileKind: grant.fileKind },
    }
  } catch (error) {
    return { status: "error", message: (error as Error).message }
  }
}

type CreateThresholdSendDependencies = {
  getIdentity: typeof getIdentity
  ensureFunded: typeof ensureFunded
  getCurrentBlock: typeof getCurrentBlock
  createThresholdGrant: typeof createThresholdGrant
  selectProtectingProvider: typeof selectProtectingProvider
}

const defaultCreateThresholdSendDependencies: CreateThresholdSendDependencies = {
  getIdentity,
  ensureFunded,
  getCurrentBlock,
  createThresholdGrant,
  selectProtectingProvider,
}

/**
 * Nominal Arkiv block time, in seconds — must match `lib/arkiv.ts`'s own
 * private `BLOCK_TIME`, which turns a TTL into the absolute block
 * `createGrant` pins. That constant is not exported and `lib/arkiv.ts` is
 * another story's file in this worktree (see docs/stories/H-53.md, "Other
 * workers are live"), so it is duplicated here rather than imported. Record
 * as a decision — see the story's `## Choices`.
 */
const NOMINAL_BLOCK_SECONDS = 2

export type CreateThresholdSendResult = {
  entityKey: string
  txHash: string
  expiresBlock: number
  expiresAt: number
  swarmRef: string
  /** The full share URL, link secret in the fragment. A different fragment per grant, even for the same asset. */
  url: string
}

/**
 * Bind, protect and write one v3, threshold-release grant against an asset
 * that already exists on Swarm — the shape `createThresholdSend` and
 * `createSendFromArchive`'s Chipotle branch both need, kept in exactly one
 * place rather than a third copy (see this story's `## Choices`).
 *
 * No upload happens here — `asset.ref` and `asset.contentKey` are reused
 * exactly as they were produced. Only the per-recipient things are fresh: a
 * random grant id, a new link secret, a newly protected key share, and one
 * new Arkiv v3 entity.
 */
async function protectAndWriteThresholdGrant(
  asset: EncryptedAsset,
  params: { recipientLabel: string; ttlSeconds: number; onProgress?: SendProgress },
  dependencies: CreateThresholdSendDependencies,
): Promise<CreateThresholdSendResult> {
  const progress = params.onProgress ?? (() => {})

  const identity = await dependencies.getIdentity()
  await dependencies.ensureFunded(identity.address)

  progress("Binding the grant")
  const currentBlock = await dependencies.getCurrentBlock()
  const expiresBlock = currentBlock + BigInt(Math.ceil(params.ttlSeconds / NOMINAL_BLOCK_SECONDS))
  const binding: GrantBinding = buildGrantBinding({
    owner: identity.address as `0x${string}`,
    expiresBlock,
    ref: asset.ref,
  })

  const linkSecret = generateLinkSecret()
  // Split first, exactly like `createSend` — one half derives from the link
  // secret and never travels; the other (`heldShare`) is what the provider
  // protects below, gated on this grant's own binding rather than handed to
  // a holder that could be asked to delete it.
  const { heldShare } = await splitContentKey(asset.contentKey, linkSecret)

  progress("Protecting the key share")
  const provider = dependencies.selectProtectingProvider()
  const protectedShare = await protectGrantShare(heldShare, linkSecret, binding, provider)

  progress("Writing grant to Arkiv")
  const payload: ThresholdGrantPayload = {
    v: 3,
    ref: asset.ref,
    release: { ...protectedShare, grantId: binding.grantId },
  }
  const grant = await dependencies.createThresholdGrant({
    privateKey: identity.privateKey,
    grantId: binding.grantId,
    expiresBlock,
    payload,
    fileKind: asset.fileKind,
    recipientBlind: await blindAttribute(identity.blindKey, params.recipientLabel),
    labelBlind: await blindAttribute(identity.blindKey, asset.labelSource),
    fileCount: asset.fileCount,
  })

  // The Arkiv entity is the only thing a release condition ever checks
  // against — see `buildArkivGrantQuery`. If what actually got written
  // disagrees with the binding this share was protected for, the provider
  // will refuse to release forever, not just late: refuse to hand out a link
  // that can never open rather than silently trusting the transaction
  // succeeded exactly as asked. See docs/stories/H-53.md, "Prevent mismatched
  // bindings".
  if (
    grant.owner.toLowerCase() !== binding.owner.toLowerCase() ||
    grant.expiresBlock !== Number(binding.expiresBlock)
  ) {
    throw new Error(
      "The threshold grant was written with an owner or expiry different from the one its key share was protected for, so it can never open — refusing to produce a link",
    )
  }

  const url = `${window.location.origin}/s/${packEntityKey(grant.entityKey)}#${toBase64Url(linkSecret)}`
  progress("Done")

  return {
    entityKey: grant.entityKey,
    txHash: grant.txHash,
    expiresBlock: grant.expiresBlock,
    expiresAt: Math.floor(Date.now() / 1000) + params.ttlSeconds,
    swarmRef: asset.ref,
    url,
  }
}

/**
 * Issue one more grant against an asset that already exists on Swarm.
 *
 * Two calls against the same asset cost one Swarm upload and two grants,
 * each with its own expiry and its own link. Protecting always goes through
 * the key-release factory (`selectProtectingProvider`), which never chooses
 * the parked TACo for a new share — see `lib/key-release/index.ts`.
 */
export async function createThresholdSend(
  asset: EncryptedAsset,
  params: { recipientLabel: string; ttlSeconds: number; onProgress?: SendProgress },
  dependencyOverrides: Partial<CreateThresholdSendDependencies> = {},
): Promise<CreateThresholdSendResult> {
  const dependencies = { ...defaultCreateThresholdSendDependencies, ...dependencyOverrides }
  return protectAndWriteThresholdGrant(asset, params, dependencies)
}

export type EndSendResult = { status: "ended" } | { status: "error"; message: string }

type EndSendDependencies = {
  getIdentity: typeof getIdentity
  getGrant: typeof getGrant
  deleteGrant: typeof deleteGrant
  fetch: typeof fetch
}

const defaultEndSendDependencies: EndSendDependencies = { getIdentity, getGrant, deleteGrant, fetch }

/**
 * End a share before its date.
 *
 * A v2/legacy grant deletes the holder's half of the content key, which is
 * what makes the link unjoinable — the Arkiv grant is left alone; this ends
 * access, not history. Proof of ownership is a signature from the sender's
 * own derived Arkiv key over the entity key, not a secret returned at create
 * time: a bearer secret would leak into logs and browser history, and anyone
 * holding it could end someone else's share.
 *
 * A v3, threshold-release grant has no holder half to delete — see
 * `lib/key-release/index.ts` and docs/stories/H-69.md, "Ending a v3 share
 * early". Deleting the entity itself, as its owner, is what "end this early"
 * has to mean instead: `dependencies.getGrant` reads the grant fresh to tell
 * the two shapes apart, and a v3 grant never reaches the holder call below.
 */
export async function endSend(
  entityKey: string,
  dependencyOverrides: Partial<EndSendDependencies> = {},
): Promise<EndSendResult> {
  const dependencies = { ...defaultEndSendDependencies, ...dependencyOverrides }
  const identity = await dependencies.getIdentity()

  let grant: Grant | null = null
  try {
    grant = await dependencies.getGrant(entityKey)
  } catch {
    // A lookup that fails does not tell us this is a v3 grant either way —
    // fall through to the holder path below, which has its own honest
    // failure handling.
  }

  if (grant && grant.payload.v === 3) {
    try {
      await dependencies.deleteGrant({ privateKey: identity.privateKey, entityKey })
      return { status: "ended" }
    } catch (error) {
      return { status: "error", message: (error as Error).message }
    }
  }

  const timestamp = Math.floor(Date.now() / 1000)
  const account = privateKeyToAccount(identity.privateKey)
  const signature = await account.signMessage({ message: revokeMessage(entityKey, timestamp) })

  const response = await dependencies.fetch("/api/holder/revoke", {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ entityKey, signature, timestamp }),
  })

  if (!response.ok) {
    const detail = await response.json().catch(() => ({}))
    return { status: "error", message: detail?.error ?? `HTTP ${response.status}` }
  }
  return { status: "ended" }
}

/** The sender's dashboard. Compound filter, owner-scoped. */
export async function listMySends(filter?: {
  fileKind?: FileKind
  createdAfter?: number
  minFiles?: number
}): Promise<Grant[]> {
  const identity = await getIdentity()
  return listGrants({ owner: identity.address, ...filter })
}
